### PR TITLE
Remove MessageLogger summary from the comparison

### PR DESCRIPTION
**Pull request by fabiocos**
To simplify comparisons, the final MessageLogger summary is removed, differences must be zero at this point

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#29841

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@smuzaffar do we need also to update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/data/cmsswdata.txt#L6 ?

**Comment by smuzaffar** [comment]
+externals
@silviodonato , once this is merged then bot will automatically open a cmsdist PR with correct changes.

**Pull request merged**
