### PR TITLE
Update MTDGeometryBuilder test reference for numerical issues on ARM/MULTIARCHS builds

### PR DESCRIPTION
**Pull request by fabiocos**
Updated reference to solve unit test failures introduced by https://github.com/cms-sw/cmssw/pull/46683 . In support of https://github.com/cms-sw/cmssw/pull/46761

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Geometry/MTDGeometryBuilder

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
this has been tested via cmssw PR, so I am merge it now

**Comment by smuzaffar** [comment]
+externals

Ref data updated used by unit test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
