### PR TITLE
Update MTD geometry reference for the dump of pixel positions

### PR DESCRIPTION
**Pull request by fabiocos**
Update of the MTDGeometryBuilder test reference to include the dump of pixel positions as computed by the RectangularMTDTopology, as added by @parbol

### CODE REVIEW

**Comment by fabiocos** [comment]
@parbol in order to test https://github.com/parbol/cmssw/commits/RectangularMTDCleaning after you open the PR, you need to use this external to get the unit test working, otherwise the reference will be different and the test will fail

**Comment by qliphy** [comment]
please test with cms-sw/cmssw#33340

**Comment by qliphy** [comment]
The differences are in line with the test results in #33340

**Comment by qliphy** [comment]
merge
(new files)

**Pull request merged**
