### PR TITLE
Initial commit with MTD geometry reference files

### PR DESCRIPTION
**Pull request by fabiocos**
Related to cms-sw/cmsdist#5832 and cms-sw/cmssw#29841

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#29841

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov as this is a brand new package, not yet in cmsdist, I am afraid this test is bound to fail, am I correct? Also the cmsdist PR should be invoked, right?

**Comment by smuzaffar** [comment]
@fabiocos , bot knows how to test cms-data PRs (even if it is new cms-data repo). So test should wok, once the Pr is merged than bot will automatically open a cmsdist PR

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#29841

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#29841

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
