### PR TITLE
Reference file for the unit test of RecoMTD/DetLayers with rounding at 4 decimal digits

### PR DESCRIPTION
**Pull request by fabiocos**
In support of cms-sw/cmssw#33762

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#33762 for slc7_aarch4_gcc9

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#33762 for slc7_ppc64le_gcc9

**Comment by fabiocos** [comment]
the proposed fix works for ppc64le

**Comment by mrodozov** [comment]
looks like it if the test doesn't fail, yes

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33762 for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
> please test with [cms-sw/cmssw#33762](https://github.com/cms-sw/cmssw/pull/33762) for slc7_aarch4_gcc9

a typo

**Comment by fabiocos** [comment]
@mrodozov it works also for aarch64

**Comment by fabiocos** [comment]
@mrodozov @silviodonato @qliphy please note that this PR without cms-sw/cmssw#33762 integrated in parallel will cause the unit test to fail also on amd64 (simply different numbers compared)

**Comment by fabiocos** [comment]
ok, I see this has not yet been propagated to cmsdist https://github.com/cms-sw/cmsdist/pull/6920

**Pull request merged**
