### PR TITLE
Update MTDGeometryBuilder test for BTL parameters

### PR DESCRIPTION
**Pull request by fabiocos**
Update of ```MTDGeometryBuilder``` test corresponding to the update of BTL parameters in cms-sw/cmssw#33453

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33453

**Comment by mrodozov** [comment]
@fabiocos it's one new file, should I merge it ?

**Comment by fabiocos** [comment]
@mrodozov this file has to go in parallel with #33453 otherwise the geometry unit test will start to fail. It it should merged at the same time of that CMSSW PR

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
