### PR TITLE
Update reference for new ETLDetId with extended module field

### PR DESCRIPTION
**Pull request by fabiocos**
This PR is needed to make the uni tests in the Geometry/MTD* packages run correctly when cms-sw/cmssw#30557 is tested.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#30557

**Comment by fabiocos** [comment]
@silviodonato the failures appear also in the latest IB, and do not look related to this PR, which on the contrary works, the unit tests for MTD packages appear to be successful (as expected, trivial update of reference to include the changed ETLDetId list).

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#30557

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#30557

**Comment by fabiocos** [comment]
hold

pending clarification of the differences noticed in comparison

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#30557

**Comment by fabiocos** [comment]
to be replaced by another PR, due to the update of the code

**Pull request closed without merging**
